export const bizType = [
  { id: 1, cdNm:'금융', cdId: "PC10" },
  { id: 2, cdNm:'기술', cdId: "PC20" },
  { id: 3, cdNm:'인력', cdId: "PC30" },
  { id: 4, cdNm:'수출', cdId: "PC40" },
  { id: 5, cdNm:'내수', cdId: "PC50" },
  { id: 6, cdNm:'창업', cdId: "PC60" },
  { id: 7, cdNm:'경영', cdId: "PC70" },
  { id: 8, cdNm:'소상공인', cdId: "PC80" },
  { id: 9, cdNm:'지원', cdId: "PC90" },
  { id: 10, cdNm:'벤처', cdId: "PC11" },
]

export const listData = [
  {
    BASE_IDX: 138974112,
    BIZTYPE: "인력",
    END_IDX: 10345673,
    PBLANCBGNDT: "2024-05-17",
    PBLANCDTLURL: "https://www.smes.go.kr/sanhakin/websquare/wq_smesDtlBsns.do?NTTSN=2158&BBSCLCODESE=00000018&BSNSCLCODESE=0000003L",
    PBLANCENDDT: "2024-05-30",
    PBLANCNM: "(경기) \"안성청사복합 통합공공임대주택\"  중소기업 근로자 국민임대 주택우선공급 확인서 발급 안내 ",
    POLICYCNTS: "<p><b> ㅇ 입주자모집공고일</b>:'24. 4. 25.(목)</p><p><b><span>※ 신청 시스템상 입주자모집공고일 날짜는 무시할 것</span></b></p><p><b><span> (실제 입주자모집공고일은 24. 4. 25. 기준) / 재직기간 산정 등도 해당 날짜 기준임</span></b></p><p><b><span><br></span></b></p><p><b> ㅇ 청약 신청접수</b>:붙임2 참조</p><p> *<u>우선공급 확인서 발급 신청 시</u>공급유형 선택 불필요</p><p><b>ㅇ'확인서 발급'신청기간</b>: '24. 5. 17.(금)~ 5. 30.(목) 18:00</p><p>  * 우선공급 확인서는 개인 이메일로 발송(이메일주소 반드시 기재)</p><p>  ** 신청서류 검토 후 확인서 발급 여부는 신청자 핸드폰 문자로 통보 예정</p>",
    REFRNC: "<p><b>ㅇ 문 의 처</b></p><p>  - 입주, 청약, 무주택요건 관련 : 031-226-3130(경기주택도시공사)</p><p>  - 확인서 발급 : 031-201-6942, 6947(경기지방중소벤처기업청)</p><p>  -산학인 시스템 오류 : 1661-7616</p>",
    REQNM: "신청가능",
    REQSTLINKINFO: "https://www.smes.go.kr/sanhakin/websquare/wq_smesDtlBsns.do?NTTSN=2158&BBSCLCODESE=00000018&BSNSCLCODESE=0000003L&RQST=Y",
    REQSTRCEPT: "<p><b>ㅇ 신청방법 : 중소기업인력지원사업 종합관리시스템(<a href=\"https://smes.go.kr/sanhakin\" target=\"_self\">https://smes.go.kr/sanhakin</a>)에서 온라인 신청</b></p>",
    SPORTINSTTNM: "중소벤처기업부",
    SPORTTRGET: "",
    SPORTTYPE: "인력지원",
    TERM: "2024-05-17 ~ 2024-05-30"
  },
  {
    BASE_IDX: 138731826,
    BIZTYPE: "소상공인",
    END_IDX: 10345673,
    PBLANCBGNDT: "2024-05-14",
    PBLANCDTLURL: "https://www.sbiz24.kr/#/pbanc/176",
    PBLANCENDDT: "2024-05-30",
    PBLANCNM: "「2024년 패키지형 스마트상점 기술보급사업」 주관기관 모집공고",
    POLICYCNTS: "<p><span>경연대회를 통해 업종별 우수한 스마트기기 패키지를 발굴하고 우수모델을 소상공인 점포에 적용하는</span><span>「</span><span>2024</span><span>년 패키지형 스마트상점</span><span></span><span>기술보급사업</span><span>」</span><span>주관기관</span><span>모집계획을 다음과 같이 공고합니다</span><span>.</span></p><p><span></span></p><p><span>2024</span><span>년</span><span>5</span><span>월</span><span>17</span><span>일</span></p><p><span>소상공인시장진흥공단 이사장</span></p>",
    REFRNC: "<p><span><span>※ </span><span>문의처</span></span></p><p><span><span></span></span></p><p><span><span>◦ </span><span>소상공인시장진흥공단 스마트상점팀 </span><span>042 – 363 – 7811</span></span></p>",
    REQNM: "신청가능",
    REQSTLINKINFO: "https://www.sbiz24.kr/#/pbanc/176",
    REQSTRCEPT: `<p><span><span>□</span></span><span><span></span><span>신청기간</span></span><span><span>: </span><span>공고게시일 </span><span>~ 5. 30(</span><span>목</span><span>) 18</span><span>시까지</span></span></p><p><span><span>□</span></span><span><span></span><span>신청방법</span></span><span><span>: </span><span>소상공인</span><span>24 </span><span>홈페이지 접수</span><span>(</span></span><a href="http://www.sbiz24.kr"><span><span>www.sbiz24.kr</span></span></a><span><span>)</span></span></p><p><span><span>□</span></span><span><span></span><span>신청서류 </span></span><span><span>: </span><span>신청기관은 아래의 제출서류를 구비하여 신청</span></span></p>`,
    SPORTINSTTNM: "소상공인시장진흥공단",
    SPORTTRGET: "",
    SPORTTYPE: "소상공인",
    TERM: "2024-05-14 ~ 2024-05-30"
  },
  {
    BASE_IDX: 138672180,
    BIZTYPE: "기술",
    END_IDX: 10345673,
    PBLANCBGNDT: "2024-04-25",
    PBLANCDTLURL: "https://www.smart-factory.kr/usr/bg/ba/ma/bsnsPblanc",
    PBLANCENDDT: "2024-05-24",
    PBLANCNM: "2024년도 제조데이터 상품가공 지원사업 공고",
    POLICYCNTS: `<p><span>경연대회를 통해 업종별 우수한 스마트기기 패키지를 발굴하고 우수모델을 소상공인 점포에 적용하는</span><span>「</span><span>2024</span><span>년 패키지형 스마트상점</span><span></span><span>기술보급사업</span><span>」</span><span>주관기관</span><span>모집계획을 다음과 같이 공고합니다</span><span>.</span></p><p><span></span></p><p><span>2024</span><span>년</span><span>5</span><span>월</span><span>17</span><span>일</span></p><p><span>소상공인시장진흥공단 이사장</span></p>""<p><span><span>중소벤처기업부 공고 제</span><span>2024-274</span><span>호</span></span></p><p><span><span></span></span></p><p><span><span>2024</span><span>년도 제조데이터 상품가공 지원사업 공고</span></span></p><p><span><span></span></span></p><p><span><span> </span></span><span><span>제조데이터 활용을 통한 국내 중소기업의 경쟁력 강화를 위하여 중소</span></span><span><span>벤처기업부에서 추진하고 있는 </span><span>2024</span><span>년도 제조데이터 상품가공 지원사업의</span></span><span><span></span><span>지원계획을 다음과 같이 공고합니다</span><span>.</span></span></p><p><span><span></span></span></p><p><span><span>2024</span><span>년 </span><span>4</span><span>월 </span><span>25</span><span>일</span></span></p><p><span><span>중소벤처기업부</span></span><span><span></span></span><span><span></span><span>장관</span></span></p>`,
    REFRNC: "<p><span>□ </span><span>문의처</span></p><p><span><span></span></span></p><table class=\"__se_tbl_ext\" cellspacing=\"0\" cellpadding=\"7\"><colgroup><col><col><col><col></colgroup><tbody><tr><td><p><span><span>구분</span></span></p></td><td colspan=\"2\"><p><span><span>기관명</span></span></p></td><td><p><span><span>연락처</span></span></p></td></tr><tr><td><p><span><span>공고문의</span></span></p></td><td><p><span><span>전담기관</span></span></p></td><td><p><span><span>스마트제조혁신추진단</span></span></p></td><td><p><span><span>044-300-0944</span></span></p></td></tr><tr><td><p><span><span>사업진행 문의</span></span></p></td><td><p><span><span>운영기관</span></span></p></td><td><p><span><span>중소기업기술혁신협회</span></span></p></td><td><p><span><span>031-628-9676</span></span></p></td></tr></tbody></table>",
    REQNM: "신청가능",
    REQSTLINKINFO: "https://www.sbiz24.kr/#/pbanc/176",
    REQSTRCEPT: "<p><span><span>◦ </span></span><span><span>(</span><span>신청기간</span><span>)</span></span><span><span></span></span><span><span>2024</span><span>년 </span><span>4</span><span>월 </span><span>25</span><span>일</span><span>(</span><span>목</span><span>) ~ 5</span><span>월 </span><span>24</span><span>일</span><span>(</span><span>금</span><span>) 17</span><span>시까지 신청</span><span>·</span><span>접수</span></span></p><p><span><span></span></span></p><p><span><span>◦ </span></span><span><span>(</span><span>신청방법</span><span>)</span></span><span><span></span></span><span><span>스마트공장 사업관리시스템</span></span><span><span>(<a href=\"http://smart-factory.kr\" target=\"_self\">smart-factory.kr</a>)</span></span><span><span></span><span>온라인 접수</span></span></p><p><span><span></span></span></p><p><span><span> - </span></span><span><span>사이트 접속 </span><span>→ </span><span>회원가입</span></span><span><span>(</span><span>기업</span><span>)</span></span><span><span>→ </span><span>과제신청 메뉴 </span><span>→ </span><span>제출서류 </span></span><span><span>다운</span></span><span><span>로드 및 작성 </span><span>→ </span><span>온라인 신청</span></span><span><span>(</span><span>제출서류 업로드</span><span>, </span><span>지원기업 아이디로 신청</span><span>)</span></span></p><p><span><span></span></span></p><p><span><span>◦</span></span><span><span>(</span><span>제출서류</span><span>)</span></span><span><span></span><span>사업신청서 및 사업자등록증명원 등</span></span><span><span>(</span><span>온라인 접수 시 첨부</span><span>)</span></span></p>",
    SPORTINSTTNM: "중소기업기술정보진흥원",
    SPORTTRGET: "",
    SPORTTYPE: "스마트공장",
    TERM: "2024-04-25 ~ 2024-05-24"
  },
];

export const listData2 = [
  {
    BASE_IDX: 1,
    CMPNY_NM: "현대해상화재보험 외4",
    CMPNY_TELNO: "1522-3556",
    CTRD_NM: "제주특별자치도",
    END_IDX: 1092,
    GRNT_IEM: "폭발.화재.붕괴.산사태.감전 상해사망.후유장해, 대중교통이용 중 상해사망.후유장해, 강도 상해사망.후유장해, 익사사고 사망, 농기계사고 상해사망.후유장해, 스쿨존 교통사고 부상치료비, 실버존 교통사고 치료비, 개 물림 사고 사망.후유장해, 개 물림 사고 응급실 내원 치료비, 급성감염병 사망 위로금, 화상수술비, 대중교통 상해부상 치료비, 자연재해 사망.후유장해, 자연재해 상해진단위로금, 사회재난 사망.후유장해, 사회재난 상해진단위로금, 상해사망.후유장해, 상해사고 진단위로금(12세이하, 65세이상)",
    HMPG_URL: "https://www.jeju.go.kr/safe/insurance/info.htm",
    LOCGOV_CHARGER_DEPT_NM: "안전정책과",
    LOCGOV_CHARGE_OFFM_TELNO: "064-710-3854",
    SBSCRB_BGNDE: "20240401",
    SBSCRB_ENDDE: "20250331",
    SBSCRB_YEAR: "2024",
    SIGNGU_NM: "(본청)"
  },
  {
    BASE_IDX: 2,
    CMPNY_NM: "메리츠화재",
    CMPNY_TELNO: "1522-3556",
    CTRD_NM: "충청북도",
    END_IDX: 1092,
    GRNT_IEM: "자연재난(풍수해 등) 사고 시 부상 치료비 보장",
    HMPG_URL: "https://www.chungbuk.go.kr/safe/index.do",
    LOCGOV_CHARGER_DEPT_NM: "안전정책과",
    LOCGOV_CHARGE_OFFM_TELNO: "043-220-2363",
    SBSCRB_BGNDE: "20240101",
    SBSCRB_ENDDE: "20241231",
    SBSCRB_YEAR: "2024",
    SIGNGU_NM: "(본청)"
  },
  {
    BASE_IDX: 3,
    CMPNY_NM: "현대해상화재보험 외4",
    CMPNY_TELNO: "1522-3556",
    CTRD_NM: "제주특별자치도",
    END_IDX: 1092,
    GRNT_IEM: "폭발.화재.붕괴.사태.감전 상해사망.후유장해, 대중교통이용 중 상해사망.후유장해, 뺑소니.무보험차 상해사망.후유장해, 강도 상해사망.후유장해, 익사사고 사망, 성폭력범죄상해 보상금, 농기계사고 상해사망.후유장해, 유독성 물질 사망, 스쿨존 교통사고 부상치료비, 실버존 교통사고 치료비, 개 물림 사고 사망.후유장해, 개 물림 사고 응급실 내원 치료비, 헌혈 후유증 보상금, 급성감염병 사망 위로금, 화상수술비, 대중교통 상해부상 치료비, 자연재해 사망.후유장해, 사회재난 사망.후유장해, 상해사망.후유장해",
    HMPG_URL: "https://www.jeju.go.kr/safe/insurance/info.htm",
    LOCGOV_CHARGER_DEPT_NM: "안전정책과",
    LOCGOV_CHARGE_OFFM_TELNO: "064-710-3854",
    SBSCRB_BGNDE: "20230401",
    SBSCRB_ENDDE: "20240331",
    SBSCRB_YEAR: "2023",
    SIGNGU_NM: "(본청)"
  },
  
]

